### PR TITLE
NS-25: Auth user + remove Taiga Ui + fix api gen

### LINKED ISSUE #25: Client: Add user auth

### PR DESCRIPTION
**Pull request by joshkhdev**
Closes #25

### CODE REVIEW

File: client-ng/src/app/shared/ui/components/button/button.interfaces.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { NsAppearance, NsColor, NsIcon, NsSize } from '../../common/types';
+
+export interface SlButtonOptions {
```
Comment (joshkhdev) [inline client-ng/src/app/shared/ui/components/button/button.interfaces.ts:3]: Rename to Ns
